spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/cursos}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update